In [26]:
## imports of dataframe and sentiment analysis
import pandas as pd
from textblob import TextBlob

In [27]:
## read in the dataset
product_review = pd.read_csv('E:\\Git_Repo\\my_sample_repo\\Input_data_sets\\amazonearphonesreviews\\AllProductReviews.csv')
product_info = pd.read_csv('E:\\Git_Repo\\my_sample_repo\\Input_data_sets\\amazonearphonesreviews\\ProductInfo.csv')

In [28]:
## checking the different product types and re-ordering
pinfo = product_info.iloc[:,[5,1,2,3,4]]
pinfo.head()

,id,Price,ProductFullName,ProductShortName,ReviewURL
0,1,1399,boAt Rockerz 255 Sports Bluetooth Wireless Ear...,boAt Rockerz 255,https://www.amazon.in/255-Bluetooth-Wireless-E...
1,2,1099,Flybot Wave in-Ear Sport Wireless Bluetooth Ea...,Flybot Wave,https://www.amazon.in/Flybot-Wireless-Bluetoot...
2,3,1099,Flybot Boom Deep Bass in-Ear Wireless Bluetoot...,Flybot Boom,https://www.amazon.in/Flybot-Wireless-Bluetoot...
3,4,749,PTron Intunes Pro Headphone Magnetic Earphone ...,PTron Intunes,https://www.amazon.in/PTron-Intunes-Pro-Smartp...
4,5,2999,Flybot Beat True Wireless Bluetooth Earphones ...,Flybot Beat,https://www.amazon.in/Flybot-Wireless-Bluetoot...

In [29]:
## Checking the review dataset
product_review.head()

,ReviewTitle,ReviewBody,ReviewStar,Product
0,Honest review of an edm music lover\n,No doubt it has a great bass and to a great ex...,3,boAt Rockerz 255
1,Unreliable earphones with high cost\n,"This earphones are unreliable, i bought it be...",1,boAt Rockerz 255
2,Really good and durable.\n,"i bought itfor 999,I purchased it second time,...",4,boAt Rockerz 255
3,stopped working in just 14 days\n,Its sound quality is adorable. overall it was ...,1,boAt Rockerz 255
4,Just Awesome Wireless Headphone under 1000...ðŸ˜‰\n,Its Awesome... Good sound quality & 8-9 hrs ba...,5,boAt Rockerz 255

In [53]:
product_review['Title_Polarity'] = ''
product_review['Title_Subjectivity'] = ''
product_review['Body_Polarity'] = ''
product_review['Body_Subjectivity'] = ''
product_review.head()

,ReviewTitle,ReviewBody,ReviewStar,Product,Title_Polarity,Title_Subjectivity,Body_Polarity,Body_Subjectivity
0,Honest review of an edm music lover\n,No doubt it has a great bass and to a great ex...,3,boAt Rockerz 255,,,,
1,Unreliable earphones with high cost\n,"This earphones are unreliable, i bought it be...",1,boAt Rockerz 255,,,,
2,Really good and durable.\n,"i bought itfor 999,I purchased it second time,...",4,boAt Rockerz 255,,,,
3,stopped working in just 14 days\n,Its sound quality is adorable. overall it was ...,1,boAt Rockerz 255,,,,
4,Just Awesome Wireless Headphone under 1000...ðŸ˜‰\n,Its Awesome... Good sound quality & 8-9 hrs ba...,5,boAt Rockerz 255,,,,

In [58]:
product_review['Title_Polarity'] = product_review['ReviewTitle'].apply(lambda tweet: TextBlob(tweet).polarity)
product_review['Title_Subjectivity'] = product_review['ReviewTitle'].apply(lambda tweet: TextBlob(tweet).subjectivity)
product_review['Body_Polarity'] = product_review['ReviewBody'].apply(lambda tweet: TextBlob(tweet).polarity)
product_review['Body_Subjectivity'] = product_review['ReviewBody'].apply(lambda tweet: TextBlob(tweet).subjectivity)
product_review.head()

,ReviewTitle,ReviewBody,ReviewStar,Product,Title_Polarity,Title_Subjectivity,Body_Polarity,Body_Subjectivity
0,Honest review of an edm music lover\n,No doubt it has a great bass and to a great ex...,3,boAt Rockerz 255,0.60,0.90,0.023077,0.496667
1,Unreliable earphones with high cost\n,"This earphones are unreliable, i bought it be...",1,boAt Rockerz 255,0.16,0.54,0.269388,0.519388
2,Really good and durable.\n,"i bought itfor 999,I purchased it second time,...",4,boAt Rockerz 255,0.70,0.60,0.150000,0.476190
3,stopped working in just 14 days\n,Its sound quality is adorable. overall it was ...,1,boAt Rockerz 255,0.00,0.00,0.400000,0.500000
4,Just Awesome Wireless Headphone under 1000...ðŸ˜‰\n,Its Awesome... Good sound quality & 8-9 hrs ba...,5,boAt Rockerz 255,1.00,1.00,0.195000,0.691111

In [59]:
product_review.describe()

,ReviewStar,Title_Polarity,Title_Subjectivity,Body_Polarity,Body_Subjectivity
count,14337.000000,14337.000000,14337.000000,14337.000000,14337.000000
mean,3.675874,0.280744,0.450148,0.286397,0.528306
std,1.503409,0.468119,0.357151,0.363310,0.242534
min,1.000000,-1.000000,0.000000,-1.000000,0.000000
25%,3.000000,0.000000,0.000000,0.000000,0.417857
50%,4.000000,0.250000,0.500000,0.300000,0.550000
75%,5.000000,0.700000,0.700000,0.550000,0.658333
max,5.000000,1.000000,1.000000,1.000000,1.000000